// export const managers = [
//   {
//     name: "Elena Marquez",
//     id: "elena",
//     trades: 6213,
//     winRate: 98.6,
//     roi: 12.4,
//     investors: 1874,
//     img: "/traders/trader1.jpg",
//     min: 500,
//   },
//   {
//     name: "Amanda Koenig",
//     id: "amanda",
//     trades: 7402,
//     winRate: 99.2,
//     roi: 15.3,
//     investors: 5458,
//     img: "/traders/trader2.jpg",
//     min: 1000,
//   },
//   {
//     name: "Youssef Nasser",
//     id: "youssef",
//     trades: 8001,
//     winRate: 98.8,
//     roi: 10.1,
//     investors: 1199,
//     img: "/traders/trader3.jpg",
//     min: 700,
//   },
//   {
//     name: "Victor Andreessen",
//     id: "victor",
//     trades: 5978,
//     winRate: 98.4,
//     roi: 13.2,
//     investors: 6084,
//     img: "/traders/trader4.jpg",
//     min: 600,
//   },
//   {
//     name: "Kolawole Afolabi",
//     id: "kolawole",
//     trades: 7850,
//     winRate: 99.7,
//     roi: 11.5,
//     investors: 987,
//     img: "/traders/trader5.jpg",
//     min: 1500,
//   },
//   {
//     name: "Thomas König",
//     id: "thomas",
//     trades: 6510,
//     winRate: 98.3,
//     roi: 14.8,
//     investors: 5951,
//     img: "/traders/trader6.jpg",
//     min: 500,
//   },
//   {
//     name: "Jasper Lin",
//     id: "jasper",
//     trades: 7122,
//     winRate: 99.1,
//     roi: 12.0,
//     investors: 1145,
//     img: "/traders/trader7.jpg",
//     min: 1000,
//   },
//   {
//     name: "Haruto Sakamoto",
//     id: "haruto",
//     trades: 6980,
//     winRate: 98.9,
//     roi: 10.5,
//     investors: 5670,
//     img: "/traders/trader8.jpg",
//     min: 1000,
//   },
//   {
//     name: "Alexei Ivanov",
//     id: "alexei",
//     trades: 8211,
//     winRate: 98.0,
//     roi: 13.0,
//     investors: 6722,
//     img: "/traders/trader9.jpg",
//     min: 500,
//   },
//   {
//     name: "Liam O’Donnell",
//     id: "liam",
//     trades: 7005,
//     winRate: 98.7,
//     roi: 11.1,
//     investors: 1832,
//     img: "/traders/trader10.jpg",
//     min: 1000,
//   },
// ];

export const withrawalData = [
  { name: "Emma Johnson from California" },
  { name: "Liam Smith from Texas" },
  { name: "Sophie Müller from Germany" },
  { name: "Noah Davis from Florida" },
  { name: "Hiroshi Tanaka from Japan" },
  { name: "Isabella Garcia from Mexico" },
  { name: "Alexander Schmidt from Germany" },
  { name: "Olivia Brown from New York" },
  { name: "Yuki Nakamura from Japan" },
  { name: "James Wilson from Ohio" },
  { name: "Lukas Fischer from Germany" },
  { name: "Ava Martinez from Spain" },
  { name: "Ethan Taylor from Georgia" },
  { name: "Mia Weber from Germany" },
  { name: "Sofia Lopez from Argentina" },
  { name: "William Anderson from Illinois" },
  { name: "Haruto Suzuki from Japan" },
  { name: "Charlotte Moore from Michigan" },
  { name: "Jonas Becker from Germany" },
  { name: "Diego Rodriguez from Colombia" },
  { name: "Amelia Thomas from Pennsylvania" },
  { name: "Klara Hoffmann from Germany" },
  { name: "Aiden Jackson from Arizona" },
  { name: "Rina Yamamoto from Japan" },
  { name: "Lucas Gonzalez from Chile" },
  { name: "Hannah White from Virginia" },
  { name: "Leon Wagner from Germany" },
  { name: "Evelyn Harris from Colorado" },
  { name: "Yuto Kimura from Japan" },
  { name: "Valeria Perez from Peru" },
  { name: "Michael Clark from Washington" },
  { name: "Anna Schneider from Germany" },
  { name: "Mason Lewis from Oregon" },
  { name: "Emi Sato from Japan" },
  { name: "Julian Morales from Venezuela" },
  { name: "Abigail Walker from Tennessee" },
  { name: "Finn Meyer from Germany" },
  { name: "Harper Young from Nevada" },
  { name: "Lena Krause from Germany" },
  { name: "Alejandro Torres from Spain" },
  { name: "Benjamin Hall from Massachusetts" },
  { name: "Kaori Ito from Japan" },
  { name: "Ella Adams from Wisconsin" },
  { name: "Maximilian Braun from Germany" },
  { name: "Camila Diaz from Mexico" },
  { name: "Daniel King from Indiana" },
  { name: "Aoi Takahashi from Japan" },
  { name: "Sophia Scott from Missouri" },
  { name: "Paul Richter from Germany" },
  { name: "Mateo Vargas from Argentina" },
  { name: "Lily Turner from Kentucky" },
  { name: "Marie Lehmann from Germany" },
  { name: "Asuka Hayashi from Japan" },
  { name: "Jackson Carter from Alabama" },
  { name: "Clara Schuster from Germany" },
  { name: "Luna Hernandez from Colombia" },
  { name: "Logan Phillips from Oklahoma" },
  { name: "Ren Osaka from Japan" },
  { name: "Grace Lee from Minnesota" },
  { name: "Niklas Wolf from Germany" },
  { name: "Santiago Alvarez from Chile" },
  { name: "Chloe Wright from Utah" },
  { name: "Julia Koch from Germany" },
  { name: "Mio Kobayashi from Japan" },
  { name: "Owen Nelson from Iowa" },
  { name: "Laura Zimmermann from Germany" },
  { name: "Gabriela Castro from Peru" },
  { name: "Elijah Baker from Kansas" },
  { name: "Hanna Vogel from Germany" },
  { name: "Kaito Fujimoto from Japan" },
  { name: "Avery Green from Nebraska" },
  { name: "Thomas Schwarz from Germany" },
  { name: "Isabel Ortiz from Venezuela" },
  { name: "Carter Mitchell from Arkansas" },
  { name: "Elisa Brandt from Germany" },
  { name: "Hana Mori from Japan" },
  { name: "Zoey Perez from Idaho" },
  { name: "Moritz Klein from Germany" },
  { name: "Javier Ruiz from Spain" },
  { name: "Madeline Cook from Louisiana" },
  { name: "Katharina Peters from Germany" },
  { name: "Sora Nishimura from Japan" },
  { name: "Gabriel Rivera from Mexico" },
  { name: "Layla Rogers from Montana" },
  { name: "Ben Hartmann from Germany" },
  { name: "Aria Evans from Wyoming" },
  { name: "Emilia Stein from Germany" },
  { name: "Riku Aoki from Japan" },
  { name: "Natalia Gomez from Argentina" },
  { name: "Henry Bailey from Delaware" },
  { name: "Lisa Krüger from Germany" },
  { name: "Yuma Kato from Japan" },
  { name: "Victoria Sanchez from Colombia" },
  { name: "Samuel Brooks from Rhode Island" },
  { name: "Timo Baumann from Germany" },
  { name: "Elena Jimenez from Spain" },
  { name: "Scarlett Morris from Connecticut" },
  { name: "Felix Lang from Germany" },
];

const additionalWithdrawalData = [
  { name: "Jacob Thompson from California" },
  { name: "Mia Rodriguez from Texas" },
  { name: "Leon Schulz from Germany" },
  { name: "Avery Bennett from Florida" },
  { name: "Takashi Yamada from Japan" },
  { name: "Valentina Morales from Mexico" },
  { name: "Sophie Wagner from Germany" },
  { name: "Lucas Harris from New York" },
  { name: "Sakura Inoue from Japan" },
  { name: "Ella Foster from Ohio" },
  { name: "Felix Neumann from Germany" },
  { name: "Camila Fernandez from Spain" },
  { name: "Nathan Carter from Georgia" },
  { name: "Emma Klein from Germany" },
  { name: "Mateo Castillo from Argentina" },
  { name: "Isabella Reed from Illinois" },
  { name: "Kenta Hashimoto from Japan" },
  { name: "Zoey Coleman from Michigan" },
  { name: "Jonas Hoffmann from Germany" },
  { name: "Santiago Ortiz from Colombia" },
  { name: "Harper Evans from Pennsylvania" },
  { name: "Lena Becker from Germany" },
  { name: "Caleb Morgan from Arizona" },
  { name: "Hina Saito from Japan" },
  { name: "Diego Vargas from Chile" },
  { name: "Lily Peterson from Virginia" },
  { name: "Maximilian Fischer from Germany" },
  { name: "Aria Sullivan from Colorado" },
  { name: "Riku Watanabe from Japan" },
  { name: "Luna Ramirez from Peru" },
  { name: "Elijah Murphy from Washington" },
  { name: "Clara Meyer from Germany" },
  { name: "Mason Brooks from Oregon" },
  { name: "Mio Nakamura from Japan" },
  { name: "Julian Alvarez from Venezuela" },
  { name: "Chloe Hayes from Tennessee" },
  { name: "Niklas Schmidt from Germany" },
  { name: "Scarlett Gordon from Nevada" },
  { name: "Anna Weber from Germany" },
  { name: "Alejandro Gomez from Spain" },
  { name: "Owen Russell from Massachusetts" },
  { name: "Yui Kobayashi from Japan" },
  { name: "Evelyn Price from Wisconsin" },
  { name: "Paul Richter from Germany" },
  { name: "Sofia Torres from Mexico" },
  { name: "Gabriel Ward from Indiana" },
  { name: "Aoi Fujimoto from Japan" },
  { name: "Amelia Cox from Missouri" },
  { name: "Thomas Braun from Germany" },
  { name: "Lucas Diaz from Argentina" },
  { name: "Layla Simmons from Kentucky" },
  { name: "Marie Schulz from Germany" },
  { name: "Asuka Mori from Japan" },
  { name: "Logan Fisher from Alabama" },
  { name: "Klara Wagner from Germany" },
  { name: "Isabel Mendoza from Colombia" },
  { name: "Carter Powell from Oklahoma" },
  { name: "Ren Takahashi from Japan" },
  { name: "Grace Perry from Minnesota" },
  { name: "Finn Hoffmann from Germany" },
  { name: "Javier Castro from Chile" },
  { name: "Ava Stewart from Utah" },
  { name: "Julia Neumann from Germany" },
  { name: "Hana Yamamoto from Japan" },
  { name: "Wyatt Jenkins from Iowa" },
  { name: "Laura Fischer from Germany" },
  { name: "Gabriela Rojas from Peru" },
  { name: "Hudson Gray from Kansas" },
  { name: "Elisa Klein from Germany" },
  { name: "Kaito Suzuki from Japan" },
  { name: "Lila Hunter from Nebraska" },
  { name: "Moritz Weber from Germany" },
  { name: "Natalia Lopez from Venezuela" },
  { name: "Nolan Bryant from Arkansas" },
  { name: "Sophie Meyer from Germany" },
  { name: "Sora Ito from Japan" },
  { name: "Zoe Freeman from Idaho" },
  { name: "Lukas Schneider from Germany" },
  { name: "Diego Jimenez from Spain" },
  { name: "Madeline Ellis from Louisiana" },
  { name: "Katharina Becker from Germany" },
  { name: "Yuma Hayashi from Japan" },
  { name: "Emiliano Rivera from Mexico" },
  { name: "Piper Walsh from Montana" },
  { name: "Ben Wagner from Germany" },
  { name: "Ellie Dunn from Wyoming" },
  { name: "Emilia Hoffmann from Germany" },
  { name: "Riku Sato from Japan" },
  { name: "Victoria Perez from Argentina" },
  { name: "Miles Tucker from Delaware" },
  { name: "Lisa Schmidt from Germany" },
  { name: "Kaori Aoki from Japan" },
  { name: "Elena Gonzalez from Colombia" },
  { name: "Grayson Knight from Rhode Island" },
  { name: "Timo Fischer from Germany" },
  { name: "Camila Morales from Spain" },
  { name: "Violet Webb from Connecticut" },
  { name: "Leon Braun from Germany" },
];

// Merge with existing data
export const withrawals = [...withrawalData, ...additionalWithdrawalData];
